// Generated by util/generate-icons.js v.0.0.1
// on Wed Sep 06 2023 18:05:43 GMT-0400 (Eastern Daylight Time).
import * as React from "react";
import { IconSvgProps } from "../../types/Icon.types";

const YoutubeIcon: React.FC<IconSvgProps> = ({
  size,
  height,
  width,
  color,
  strokeWidth = 1,
  ...rest
}: IconSvgProps) => {
  return (
    <svg
  width={size || width}
  height={size || height}
  viewBox="0 0 32 32"
  fill="none"
  xmlns="http://www.w3.org/2000/svg"
  {...rest}
>
  <path
    fillRule="evenodd"
    clipRule="evenodd"
    d="M25.7669 7.77223C26.8433 8.06034 27.6892 8.90616 27.9773 9.98248C28.498 11.9313 28.5 16 28.5 16C28.5 16 28.5 20.0685 27.9773 22.0174C27.6892 23.0937 26.8433 23.9395 25.7669 24.2276C23.8182 24.7503 16 24.7503 16 24.7503C16 24.7503 8.18183 24.7503 6.23295 24.2276C5.15665 23.9395 4.31083 23.0937 4.02272 22.0174C3.5 20.0685 3.5 16 3.5 16C3.5 16 3.5 11.9313 4.02272 9.98248C4.31083 8.90616 5.15665 8.06034 6.23295 7.77223C8.18183 7.24951 16 7.24951 16 7.24951C16 7.24951 23.8182 7.24951 25.7669 7.77223ZM19.9925 16.0003L13.4976 19.7499V12.2507L19.9925 16.0003Z"
    stroke={color}
    strokeWidth={strokeWidth}
    strokeLinejoin="round"
  />
</svg>

  );
};

export default YoutubeIcon;
