// Generated by util/create-component.ts v.0.0.1
// on Tue Sep 05 2023 11:22:11 GMT-0400 (Eastern Daylight Time).
import React from "react";
import { IconProps } from "../types/Icon.types";
import Color from "../types/Colors.type";
import icons from "./Icon.map";

const Icon: React.FC<IconProps> = ({
  icon,
  size = 32,
  color = "primary",
  ...rest
}) => {
  let IconComponent = icons[icon].component;
  if (!IconComponent) {
    console.error(`Icon '${icon}' not found`);
    return null;
  }

  return <IconComponent size={size} color={Color[color]} {...rest} />;
};

export default Icon;
