// Generated by util/generate-iconmap.js v.0.0.1
// on Wed Sep 06 2023 17:08:38 GMT-0400 (Eastern Daylight Time)
import { IconMap, iconCategories } from "../types/Icon.types";
import Linkedin from "./icons/Linkedin";
import Twitter from "./icons/Twitter";
import Youtube from "./icons/Youtube";

const icons: IconMap = {
  linkedin: {
    component: Linkedin,
    category: iconCategories.brand as keyof typeof iconCategories,
  },
  twitter: {
    component: Twitter,
    category: iconCategories.brand as keyof typeof iconCategories,
  },
  youtube: {
    component: Youtube,
    category: iconCategories.brand as keyof typeof iconCategories,
  },
};

export default icons;
